import { check, index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { desc, sql } from "drizzle-orm";

export const marketPredictions = sqliteTable("market_predictions", {
  predictionKey: text("prediction_key").primaryKey(),
  matchId: integer("match_id").notNull(),
  matchDate: text("match_date").notNull(),
  kickoffTime: text("kickoff_time").notNull(),
  homeTeam: text("home_team").notNull(),
  awayTeam: text("away_team").notNull(),
  marketIndex: integer("market_index").notNull(),
  marketType: text("market_type").notNull(),
  marketCondition: text("market_condition").notNull(),
  betmanRound: text("betman_round"),
  matchSeq: text("match_seq"),
  optionsJson: text("options_json").notNull(),
  probabilitySum: real("probability_sum").notNull(),
  savedAt: text("saved_at").notNull(),
  selectedOptionIndex: integer("selected_option_index"),
}, (table) => [
  index("idx_market_predictions_saved_at").on(table.savedAt),
  check("ck_market_predictions_selected_option", sql`${table.selectedOptionIndex} is null or ${table.selectedOptionIndex} between 0 and 2`),
]);

export const betmanRoundSources = sqliteTable("betman_round_sources", {
  slot: integer("slot").primaryKey(),
  sourceUrl: text("source_url").notNull(),
  gmId: text("gm_id").notNull(),
  gmTs: text("gm_ts").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const betmanHistoryRounds = sqliteTable("betman_history_rounds", {
  roundKey: text("round_key").primaryKey(),
  gmId: text("gm_id").notNull(),
  gmTs: text("gm_ts").notNull(),
  sourceUrl: text("source_url").notNull(),
  status: text("status").notNull(),
  providerFinal: integer("provider_final").notNull().default(0),
  eventFrom: text("event_from"),
  eventTo: text("event_to"),
  attemptCount: integer("attempt_count").notNull().default(0),
  lastAttemptAt: text("last_attempt_at"),
  lastSuccessAt: text("last_success_at"),
  finalizedAt: text("finalized_at"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  leaseExpiresAt: text("lease_expires_at"),
  leaseToken: text("lease_token"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("uq_betman_history_round").on(table.gmId, table.gmTs),
  index("idx_betman_history_rounds_status_range").on(table.status, table.eventFrom, table.eventTo),
  check("ck_betman_history_round_gm", sql`${table.gmId} = 'G101'`),
]);

export const betmanHistoryMatches = sqliteTable("betman_history_matches", {
  sourceKey: text("source_key").primaryKey(),
  roundKey: text("round_key").notNull().references(() => betmanHistoryRounds.roundKey),
  gmId: text("gm_id").notNull(),
  gmTs: text("gm_ts").notNull(),
  matchSeq: text("match_seq").notNull(),
  leagueCode: text("league_code").notNull(),
  leagueName: text("league_name").notNull(),
  betmanLeagueName: text("betman_league_name").notNull(),
  kickoffAt: text("kickoff_at").notNull(),
  matchDate: text("match_date").notNull(),
  homeTeamId: integer("home_team_id"),
  awayTeamId: integer("away_team_id"),
  homeTeamName: text("home_team_name"),
  awayTeamName: text("away_team_name"),
  betmanHomeTeam: text("betman_home_team").notNull(),
  betmanAwayTeam: text("betman_away_team").notNull(),
  homeScore: integer("home_score"),
  awayScore: integer("away_score"),
  result: text("result"),
  homeOdds: real("home_odds"),
  drawOdds: real("draw_odds"),
  awayOdds: real("away_odds"),
  displayStatus: text("display_status").notNull(),
  sourceFinal: integer("source_final").notNull().default(0),
  firstSeenAt: text("first_seen_at").notNull(),
  lastSeenAt: text("last_seen_at").notNull(),
  finalizedAt: text("finalized_at"),
}, (table) => [
  uniqueIndex("uq_betman_history_match_source").on(table.gmId, table.gmTs, table.matchSeq),
  index("idx_betman_history_matches_status_date").on(table.displayStatus, desc(table.matchDate), desc(table.kickoffAt)),
  index("idx_betman_history_matches_league_date").on(table.leagueCode, desc(table.matchDate), desc(table.kickoffAt)),
  index("idx_betman_history_matches_home_date").on(table.leagueCode, table.homeTeamId, desc(table.matchDate)),
  index("idx_betman_history_matches_away_date").on(table.leagueCode, table.awayTeamId, desc(table.matchDate)),
  index("idx_betman_history_matches_round").on(table.roundKey),
  check("ck_betman_history_match_league", sql`${table.leagueCode} in ('K1', 'J1')`),
  check("ck_betman_history_match_result", sql`${table.result} is null or ${table.result} in ('H', 'D', 'A')`),
  check("ck_betman_history_match_status", sql`${table.displayStatus} in ('INCLUDED', 'CANCELLED', 'PENDING_RESULT', 'MISSING_ODDS', 'TEAM_MATCH_FAILED')`),
]);
